projectname: jackpotvillage
projectPrettyName: JPV - Retargeting
platform: Sizmek
sizes:
  160x600:
    link: https://google.com/
  300x250:
    link: https://google.com/
  728x90:
    link:
  300x600:
    link:
  320x50:
    link:
  120x600:
    link:
  468x90:
    link:
