projectname: jackpotvillage
projectPrettyName: Jackpot Village
platform: Sizmek
sizes:
  160x600:
    link: https://google.com/
  300x600:
    link: https://google.com/
  728x90:
    link:
  500x90:
    link:
