projectname: jackpotvillage
projectPrettyName: JPV - Retargeting
platform: Sizmek
sizes:
  160x600:
    link: https://www.jackpotvillage.com/
  300x250:
    link: https://www.jackpotvillage.com/
  728x90:
    link: https://www.jackpotvillage.com/
  300x600:
    link: https://www.jackpotvillage.com/
  320x50:
    link: https://www.jackpotvillage.com/
  120x600:
    link: https://www.jackpotvillage.com/
  468x90:
    link: https://www.jackpotvillage.com/
